version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15000:15000"
    environment:
      - WHYNOT_SETTINGS=default_settings.py
    command: gunicorn -k gevent -b 0.0.0.0:15000 whynot_web.application:app
    volumes:
        - /srv/data:/data
